#define OV7670_I2C_ADDR        0x42

#define REG_COM1               0x04
#define REG_COM2               0x09
#define REG_COM3               0x0C
#define REG_COM4               0x0D
#define REG_COM5               0x0E
#define REG_COM6               0x0F
#define REG_COM7               0x12
#define REG_COM8               0x13
#define REG_COM9               0x14
#define REG_COM10              0x15
#define REG_COM11              0x3B
#define REG_COM12              0x3C
#define REG_COM13              0x3D
#define REG_COM14              0x3E
#define REG_COM15              0x40
#define REG_COM16              0x41
#define REG_COM17              0x42

#define REG_GAIN               0x00
#define REG_BLUE               0x01
#define REG_RED                0x02
#define REG_VREF               0x03
#define REG_BAVE               0x05
#define REG_GBAVE              0x06
#define REG_AECHH              0x07
#define REG_RAVE               0x08
#define REG_PID                0x0A
#define REG_VER                0x0B
#define REG_AECH               0x10
#define REG_CLKRC              0x11
#define REG_HSTART             0x17
#define REG_HSTOP              0x18
#define REG_VSTART             0x19
#define REG_VSTOP              0x1A
#define REG_PSHFT              0x1B
#define REG_MIDH               0x1C
#define REG_MIDL               0x1D
#define REG_MVFP               0x1E
#define REG_LAEC               0x1F
#define REG_ADCCTR0            0x20
#define REG_ADCCTR1            0x21
#define REG_ADCCTR2            0x22
#define REG_ADCCTR3            0x23
#define REG_AEW                0x24
#define REG_AEB                0x25
#define REG_VPT                0x26
#define REG_BBIAS              0x27
#define REG_GBBIAS             0x28
#define REG_EXHCH              0x2A
#define REG_EXHCL              0x2B
#define REG_RBIAS              0x2C
#define REG_ADVFL              0x2D
#define REG_ADVFH              0x2E
#define REG_YAVE               0x2F
#define REG_HSYST              0x30
#define REG_HSYEN              0x31
#define REG_HREF               0x32
#define REG_CHLF               0x33
#define REG_ARBLM              0x34
#define REG_ADC                0x37
#define REG_ACOM               0x38
#define REG_OFON               0x39
#define REG_TSLB               0x3A
#define REG_EDGE               0x3F
#define REG_AWBC1              0x43
#define REG_AWBC2              0x44
#define REG_AWBC3              0x45
#define REG_AWBC4              0x46
#define REG_AWBC5              0x47
#define REG_AWBC6              0x48
#define REG_REG4B              0x4B
#define REG_DNSTH              0x4C
#define REG_MTX1               0x4F
#define REG_MTX2               0x50
#define REG_MTX3               0x51
#define REG_MTX4               0x52
#define REG_MTX5               0x53
#define REG_MTX6               0x54
#define REG_BRIGHT             0x55
#define REG_CONTRAS            0x56
#define REG_CONTRASCENTER      0x57
#define REG_MTXS               0x58
#define REG_LCC1               0x62
#define REG_LCC2               0x63
#define REG_LCC3               0x64
#define REG_LCC4               0x65
#define REG_LCC5               0x66
#define REG_MANU               0x67
#define REG_MANV               0x68
#define REG_GFIX               0x69
#define REG_GGAIN              0x6A
#define REG_DBLV               0x6B
#define REG_AWBCTR3            0x6C
#define REG_AWBCTR2            0x6D
#define REG_AWBCTR1            0x6E
#define REG_AWBCTR0            0x6F
#define REG_SCALING_XSC        0x70
#define REG_SCALING_YSC        0x71
#define REG_SCALING_DCWCTR     0x72
#define REG_SCALING_PCLK_DIV   0x73
#define REG_REG74              0x74
#define REG_REG75              0x75
#define REG_REG76              0x76
#define REG_REG77              0x77
#define REG_SLOP               0x7A
#define REG_GAM1               0x7B
#define REG_GAM2               0x7C
#define REG_GAM3               0x7D
#define REG_GAM4               0x7E
#define REG_GAM5               0x7F
#define REG_GAM6               0x80
#define REG_GAM7               0x81
#define REG_GAM8               0x82
#define REG_GAM9               0x83
#define REG_GAM10              0x84
#define REG_GAM11              0x85
#define REG_GAM12              0x86
#define REG_GAM13              0x87
#define REG_GAM14              0x88
#define REG_GAM15              0x89
#define REG_RGB444             0x8C
#define REG_DM_LNL             0x92
#define REG_DM_LNH             0x93
#define REG_LCC6               0x94
#define REG_LCC7               0x95
#define REG_BD50ST             0x9D
#define REG_BD60ST             0x9E
#define REG_HAECC1             0x9F
#define REG_HAECC2             0xA0
#define REG_SCALING_PCLK_DELAY 0xA2
#define REG_NT_CTRL            0xA4
#define REG_BD50MAX            0xA5
#define REG_HAECC3             0xA6
#define REG_HAECC4             0xA7
#define REG_HAECC5             0xA8
#define REG_HAECC6             0xA9
#define REG_HAECC7             0xAA
#define REG_BD60MAX            0xAB
#define REG_STROPT             0xAC
#define REG_STR_R              0xAD
#define REG_STR_G              0xAE
#define REG_STR_B              0xAF
#define REG_ABLC1              0xB1
#define REG_THL_ST             0xB3
#define REG_THL_DLT            0xB5
#define REG_ADCHB              0xBE
#define REG_ADCHR              0xBF
#define REG_ADCHGB             0xC0
#define REG_ADCHGR             0xC1
#define REG_SATCTR             0xC9

//*************************************************************************************//

#define MSK_COM7               0x40
#define MSK_COM15              0x0F
#define MSK_CLKRC              0x80
#define MSK_DBLV               0x2F
#define MSK_RGB444             0xFC

//*************************************************************************************//

#define COM3_SWAP              0x40
#define COM3_SCALEEN           0x08
#define COM3_DCWEN             0x04
#define COM7_RESET             0x80
#define COM7_VGA               0x00
#define COM7_CIF               0x20
#define COM7_QVGA              0x10
#define COM7_QCIF              0x08
#define COM7_CBAR              0x02
#define COM7_YUV               0x00
#define COM7_RGB               0x04
#define COM7_BAYER             0x01
#define COM7_PBAYER            0x05
#define COM8_FASTAEC           0x80
#define COM8_AECSTE            0x40
#define COM8_BFILT             0x20
#define COM8_AGC               0x04
#define COM8_AWB               0x02
#define COM8_AEC               0x01
#define COM14_CLKEN            0x10
#define COM14_MANEN            0x08
#define COM14_DIV16            0x04
#define COM14_DIV8             0x03
#define COM14_DIV4             0x02
#define COM14_DIV2             0x01
#define COM14_DIV1             0x00
#define COM15_R00FF            0xC0
#define COM15_R01FE            0x80
#define COM15_R10F0            0x00
#define COM15_RGB555           0x30
#define COM15_RGB565           0x10
#define COM16_AWBGAIN          0x08
#define COM17_CBAR             0x08

#define CLKRC_EXT              0x40
#define DBLV_PPL1              0x00
#define DBLV_PPL4              0x40
#define DBLV_PPL6              0x80
#define DBLV_PPL8              0xC0
#define DBLV_IREG              0x10
#define RGB444_EN              0x02
#define RGB444_xRGB            0x00
#define RGB444_RGBx            0x01
#define TSLB_AUTO              0x01